# -*- coding: utf-8 -*-
"""Python.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uVPkDUrksE_6Ut-WUqUSbGUVD2j33O1T
"""

import gspread
import pandas as pd
from oauth2client.service_account import ServiceAccountCredentials
import json
from google.colab import userdata
from io import StringIO

# --- Autenticação ---
scopes = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]

creds_json = userdata.get('GSPREAD_CREDENTIALS')
creds_dict = json.loads(creds_json)
creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_dict, scopes)
gc = gspread.authorize(creds)

# --- Abrir planilha ---
spreadsheet_id = "17bbpy_WPxNgCoS_u5z6yKifey77q4gKvc-4LlRl3b0Y"
sh = gc.open_by_key(spreadsheet_id)
worksheet = sh.get_worksheet(0)  # primeira aba (Planilha1)


texto = worksheet.acell("A1").value


texto_formatado = texto.replace(" ", "\n")


df = pd.read_csv(StringIO(texto_formatado), sep=",", header=0)

print("DataFrame organizado:")
print(df.head())


try:
    worksheet2 = sh.worksheet("Planilha2")
except gspread.exceptions.WorksheetNotFound:
    worksheet2 = sh.add_worksheet(title="Planilha2", rows="100", cols="20")

worksheet2.clear()
worksheet2.update([df.columns.values.tolist()] + df.values.tolist())

# --- Imports ---
import gspread
import pandas as pd
from oauth2client.service_account import ServiceAccountCredentials
import json
from google.colab import userdata
import matplotlib.pyplot as plt
import seaborn as sns

# --- Autenticação ---
scopes = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]
creds_json = userdata.get('GSPREAD_CREDENTIALS')
creds_dict = json.loads(creds_json)
creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_dict, scopes)
gc = gspread.authorize(creds)

# --- Abrir planilha ---
spreadsheet_id = "17bbpy_WPxNgCoS_u5z6yKifey77q4gKvc-4LlRl3b0Y"
sh = gc.open_by_key(spreadsheet_id)


worksheet = sh.worksheet("Planilha2")


data = worksheet.get_all_values()


df = pd.DataFrame(data[1:], columns=data[0])


df["total_conta"] = pd.to_numeric(df["total_conta"], errors="coerce")
df["gorjeta"] = pd.to_numeric(df["gorjeta"], errors="coerce")
df["quantidade"] = pd.to_numeric(df["quantidade"], errors="coerce")


#1. Gráfico de Densidade do total de gorjetas por sexo
plt.figure(figsize=(8,5))
sns.kdeplot(data=df, x="gorjeta", hue="sexo", fill=True, common_norm=False, alpha=0.5)
plt.title("Densidade do Total de Gorjetas por Sexo")
plt.xlabel("Valor da Gorjeta")
plt.ylabel("Densidade")
plt.show()

#2. Gráfico de Densidade do total de gorjetas pela quantidade de pessoas
plt.figure(figsize=(8,5))
sns.kdeplot(data=df, x="gorjeta", hue="quantidade", fill=True, common_norm=False, alpha=0.5)
plt.title("Densidade do Total de Gorjetas pela Quantidade de Pessoas na Mesa")
plt.xlabel("Valor da Gorjeta")
plt.ylabel("Densidade")
plt.show()

#3. Gráfico de Densidade do total de gorjetas por dia da semana
plt.figure(figsize=(8,5))
sns.kdeplot(data=df, x="gorjeta", hue="dia", fill=True, common_norm=False, alpha=0.5)
plt.title("Densidade do Total de Gorjetas por Dia da Semana")
plt.xlabel("Valor da Gorjeta")
plt.ylabel("Densidade")
plt.show()
